# Generated by Django 4.2.6 on 2023-11-12 10:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default_user_dp.png', help_text='Help us recognize you better. ;)', upload_to=users.models.Profile.dp_directory_path, verbose_name='Display Photo: '),
        ),
    ]
