# Generated by Django 4.2.6 on 2023-11-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_type',
            field=models.ForeignKey(blank=True, default='Advisor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeetype'),
        ),
    ]
