# Generated by Django 4.2.6 on 2024-01-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='allowed_leaves_per_day',
            field=models.PositiveIntegerField(blank=True, default=20, help_text='\n            This will help with auto-approve leave requests.\n            Computation will be: allowed leaves - approved leaves for the day. If there are still available allowed_leaves_per_day instances, the leave requests will be auto-approved.\n            If there are none, the leave status will just be set to default: "Pending".\n        ', null=True),
        ),
    ]
