# Generated by Django 4.2.6 on 2023-11-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetype',
            name='name',
            field=models.CharField(choices=[('Advisor', 'Advisor'), ('Team Leader', 'Team Leader'), ('Operations Manager', 'Operations Mgr')], default='Advisor', max_length=80, verbose_name='Employee Type: '),
        ),
    ]
