# Generated by Django 4.2.6 on 2023-11-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employeetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='name',
            field=models.CharField(blank=True, choices=[('FST', 'Fst'), ('AUH', 'Auh'), ('ASP', 'Asp'), ('MSS', 'Mss'), ('HRS', 'Hrs'), ('US', 'Us'), ('CANADA', 'Canada')], max_length=80, verbose_name='Workgroup: '),
        ),
    ]
