# Generated by Django 4.2.6 on 2023-11-15 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_workgroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('ext_name', models.CharField(blank=True, max_length=3, verbose_name='Extension')),
                ('image', models.ImageField(blank=True, default='defaults/round.png', upload_to=users.models.Profile.dp_directory_path, verbose_name='Photo')),
                ('emp_type', models.ForeignKey(blank=True, default='Advisor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeetype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workgroup', models.ForeignKey(blank=True, default='US', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.workgroup')),
            ],
        ),
    ]
