# Generated by Django 4.2.6 on 2023-12-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_operations_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emp_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='workgroup',
        ),
    ]
