# Generated by Django 4.2.6 on 2023-11-16 00:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emp_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='workgroup',
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='name',
            field=models.CharField(blank=True, choices=[('Advisor', 'Advisor'), ('Team Leader', 'Team Leader'), ('Operations Manager', 'Operations Mgr')], max_length=80, verbose_name='Employee Type: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default_user_dp.png', upload_to=users.models.Profile.dp_directory_path, verbose_name='Photo'),
        ),
    ]
