# Generated by Django 4.2.6 on 2023-11-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_date_joined_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, choices=[('FST', 'Fst'), ('AUH', 'Auh'), ('ASP', 'Asp'), ('MSS', 'Mss'), ('HRS', 'Hrs'), ('US', 'Us'), ('CANADA', 'Canada')], default='US', max_length=80, verbose_name='Workgroup: ')),
            ],
        ),
    ]
