# Generated by Django 4.2.6 on 2023-11-14 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.workgroup'),
        ),
    ]
