# Generated by Django 4.2.6 on 2023-11-20 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecounter',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_filer', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.leavetype', verbose_name='Leave Type'),
        ),
        migrations.AddField(
            model_name='leave',
            name='recipients',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__in': ['Advisor', 'Team Leader']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
