# Generated by Django 4.2.6 on 2023-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecounter',
            name='last_quarter_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavecounter',
            name='last_year_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
