# Generated by Django 4.2.6 on 2023-11-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='recipients',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__in': ['Advisor', 'Team Leader']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approver', to='users.profile'),
        ),
    ]
