# Generated by Django 4.2.6 on 2023-11-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_leavecounter_last_quarter_reset_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecounter',
            name='total_approved_per_quarter',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
