# Generated by Django 4.2.6 on 2024-01-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecounter',
            name='reset_this_quarter',
            field=models.BooleanField(default=False),
        ),
    ]
