# Generated by Django 4.2.6 on 2024-01-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_leavecounter_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
