# Generated by Django 4.2.6 on 2024-04-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_leavecounter_reset_this_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecounter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leavecounter',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='leavecounter',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
