# Generated by Django 4.2.6 on 2024-04-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_leavecounter_created_leavecounter_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavecounter',
            name='created',
        ),
        migrations.RemoveField(
            model_name='leavecounter',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='leavecounter',
            name='note',
        ),
        migrations.AddField(
            model_name='leave',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavecounter',
            name='reset_this_year',
            field=models.BooleanField(default=False),
        ),
    ]
