# Generated by Django 4.2.6 on 2023-11-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_leave_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecounter',
            name='additional_instances',
            field=models.PositiveIntegerField(default=0, verbose_name='Additional Instances'),
        ),
    ]
