# Generated by Django 4.2.6 on 2023-12-08 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_leavecounter_additional_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecounter',
            name='additional_instances',
            field=models.PositiveIntegerField(default=0, help_text='Please note that these additional instances need to be updated per quarter as they may allow too many leave instances PER_QUARTER for every employee that had this attribute changed (default=0).', verbose_name='Additional Instances'),
        ),
        migrations.AlterField(
            model_name='leavecounter',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
    ]
