# Generated by Django 4.2.6 on 2024-01-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_leavecounter_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavecounter',
            name='reset_this_year',
        ),
    ]
