# Generated by Django 4.2.6 on 2023-12-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_leavecounter_total_approved_per_quarter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavecounter',
            old_name='total_approved_per_quarter',
            new_name='max_approved_per_quarter',
        ),
        migrations.RenameField(
            model_name='leavecounter',
            old_name='total_instances_per_year',
            new_name='max_instances_per_year',
        ),
    ]
