# Generated by Django 4.2.6 on 2023-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_total_approved_per_quarter_leavecounter_max_approved_per_quarter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavecounter',
            name='additional_instances',
        ),
        migrations.RemoveField(
            model_name='leavecounter',
            name='max_approved_per_quarter',
        ),
        migrations.AddField(
            model_name='leavecounter',
            name='additional_instances_per_quarter',
            field=models.PositiveIntegerField(default=0, verbose_name='Additional Instances Per Quarter'),
        ),
        migrations.AddField(
            model_name='leavecounter',
            name='additional_instances_per_year',
            field=models.PositiveIntegerField(default=0, verbose_name='Additional Instances Per Year'),
        ),
        migrations.AddField(
            model_name='leavecounter',
            name='max_instances_per_quarter',
            field=models.PositiveIntegerField(default=6, help_text="This count shows the default. Always check for 'additional_instances' for the actual computation of the max_allowed instances per_year and per_quarter.", verbose_name='Max. Instances Per Quarter'),
        ),
        migrations.AlterField(
            model_name='leavecounter',
            name='max_instances_per_year',
            field=models.PositiveIntegerField(default=25, help_text="This count shows the default. Always check for 'additional_instances' for the actual computation of the max_allowed instances per_year and per_quarter.", verbose_name='Max. Instances Per Year'),
        ),
    ]
